export const MESSAGES = {
	ID_REQUIRED: "must send id",
	INVALID_TOKEN: "invalid token",
	LOGIN_ERROR: "email or password was not correct",
	PRODUCT_ID_REQUIRED: "must send the product id",
	PRODUCT_NOT_FOUND: "product not found",
	PRODUCT_REQUIRED_FIELDS: "must send body",
	QUERY_BODY_REQUIRED: "the request body must be passed",
	SALE_NOT_FOUND: "sale not found",
	SALE_REQUIRED_FIELDS: "must send the items",
	SALE_WITHOUT_STOCK:"products without stock",
	TOKEN_REQUIRED: "authorization header is required",
	USER_CREATED: "user created successfully",
	USER_EXIST: "user already exists",
	USER_INACTIVE: "inactive user",
	USER_LOGOUT: "user successfully logged out",
	USER_NOT_FOUND: "user not found",
	USER_UNAUTHORIZED: "user is not authorized",
	STATS_NOT_FOUND: "stats not found",
	VARIANT_NOT_FOUND: "variant not found",
};
